app:
  name: core
  log_level: info
  api:
    api_type: grpc
    server_address: 0.0.0.0:50051
  infrastructure:
    clients:
      camera_service:
        instances:
          - id: 0
            address: 0.0.0.0:50052
          - id: 1
            address: 0.0.0.0:50053
          - id: 2
            address: 0.0.0.0:50054
          - id: 3
            address: 0.0.0.0:50055
