app:
  name: sensor-core
  log_level: debug
  api:
    api_type: rest
    server_address: 0.0.0.0:3000
  infrastructure:
    clients:
      camera_service:
        instances:
          - id: 0
            address: frontier-peripheral-ctrl-mpsoc.local:50050
          - id: 1
            address: frontier-peripheral-ctrl-mpsoc.local:50051
          - id: 2
            address: frontier-peripheral-ctrl-mpsoc.local:50052
          - id: 3
            address: frontier-peripheral-ctrl-mpsoc.local:50053
      video_service:
        instances:
          - id: 0
            address: localhost:50060
          - id: 1
            address: localhost:50061
          - id: 2
            address: localhost:50062
          - id: 3
            address: localhost:50063