app:
  name: sensor-core
  log_level: debug
  api:
    api_type: rest
    server: 0.0.0.0
    port: 3000
  infrastructure:
    clients:
      camera_service:
        instances:
          - id: 0
            server: frontier-peripheral-ctrl-mpsoc.local
            port: 50050
          - id: 1
            server: frontier-peripheral-ctrl-mpsoc.local
            port: 50051
          - id: 2
            server: frontier-peripheral-ctrl-mpsoc.local
            port: 50052
          - id: 3
            server: frontier-peripheral-ctrl-mpsoc.local
            port: 50053
      video_service:
        instances:
          - id: 0
            server: localhost
            port: 50060
          - id: 1
            server: localhost
            port: 50061
          - id: 2
            server: localhost
            port: 50062
          - id: 3
            server: localhost
            port: 50063