name: Test

on:
  push:
  pull_request:
    types:
      - opened

env:
  BUILD_TYPE: Release
  BUILD_DIR: build-native

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get the project name
        run: |
          echo "PROJECT_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Build
        run: ./scripts/build.sh native

      - name: Test
        run: cd ./${{ env.BUILD_DIR }}/$sub_project && ./$bin
        env:
          sub_project: tests
          bin: ${{ env.PROJECT_NAME }}-unit-tests

      - name: Create coverage reports
        if: github.event_name == 'push'
        run: |
          pip install gcovr
          gcovr --xml coverage_report.xml --exclude '.*tests.*' --exclude '.*build.*'
          gcovr --exclude '.*tests.*' --exclude '.*build.*'
          rm -rf ./${{ env.BUILD_DIR }}/tests

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}